// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaOlmL5mX-jJzS-eUXScQL6MsaTC_mQ9o',
    appId: '1:573261496812:web:1217c9484eceb168bf40c9',
    messagingSenderId: '573261496812',
    projectId: 'middleapp-88634',
    authDomain: 'middleapp-88634.firebaseapp.com',
    storageBucket: 'middleapp-88634.appspot.com',
    measurementId: 'G-02DE213WT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBmD6gf4BRt_qH-M2CFBo0PNF_oIUSu2s',
    appId: '1:573261496812:android:0f288da0a1e7cc44bf40c9',
    messagingSenderId: '573261496812',
    projectId: 'middleapp-88634',
    storageBucket: 'middleapp-88634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxGa3dTb6UG3zQVMWLeDYJos7nhQPLl3k',
    appId: '1:573261496812:ios:d30a55ed44e16aa4bf40c9',
    messagingSenderId: '573261496812',
    projectId: 'middleapp-88634',
    storageBucket: 'middleapp-88634.appspot.com',
    iosBundleId: 'com.example.middleapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxGa3dTb6UG3zQVMWLeDYJos7nhQPLl3k',
    appId: '1:573261496812:ios:d30a55ed44e16aa4bf40c9',
    messagingSenderId: '573261496812',
    projectId: 'middleapp-88634',
    storageBucket: 'middleapp-88634.appspot.com',
    iosBundleId: 'com.example.middleapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaOlmL5mX-jJzS-eUXScQL6MsaTC_mQ9o',
    appId: '1:573261496812:web:3e16eddb61a63317bf40c9',
    messagingSenderId: '573261496812',
    projectId: 'middleapp-88634',
    authDomain: 'middleapp-88634.firebaseapp.com',
    storageBucket: 'middleapp-88634.appspot.com',
    measurementId: 'G-D91GD9WQ2E',
  );
}
